changeLogFile=changelog/db.changelog-master.xml
url=jdbc:postgresql://localhost:5432/home_account_db
username=vasmanuel
password=12569812
driver=org.postgresql.Driver

#classpath=./lib/postgresql-42.7.3.jar
